services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    env_file:
      - .env
    deploy:
      replicas: 2
    command: celery -A app.celery_app worker --loglevel=info

volumes:
  uploaded_files: 