services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8202

  backend:
    build: ./backend
    ports:
      - "8202:8000"
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    env_file:
      - .env
    # deploy: 定义服务的部署和运行时配置
    # replicas: 指定要运行的容器副本数量，这里设置为2表示会同时运行2个相同的容器实例
    # 适用场景：
    # 1. 高可用：某个实例故障时，另一个实例仍能提供服务
    # 2. 负载均衡：请求可以分散到多个实例上
    # 3. 零停机部署：更新时可以逐个替换实例
    deploy:
      replicas: 2
    command: celery -A app.celery_app worker --loglevel=info

volumes:
  uploaded_files: 