name: dp gpt

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to ghrc
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: zhenda-hub
          password: ${{ secrets.GHCR_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./pj1
          push: true
          tags: |
            zzdnb/word-cloud-gene:${{ github.sha }}
            zzdnb/word-cloud-gene:latest
            ghcr.io/zhenda-hub/word-cloud-gene:${{ github.sha }}
            ghcr.io/zhenda-hub/word-cloud-gene:latest

      # - name: Build Docker Image
      #   run: |
      #     cd pj1
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA .
      #     docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
      
      # - name: Push Docker Image
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA
      #     docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          username: ${{ secrets.TENCENT_USERNAME }}
          key: ${{ secrets.TENCENT_PRI_SSH_KEY }}
          # password: ${{ secrets.TENCENT_PASSWORD }}
          script: |
            cd /www/wwwroot/docker-django-demo
            git pull
            sudo docker compose up --build -d
